spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanagement
    username: root
    password: 123456789

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  thymeleaf:
    cache: false

server:
  port: 8082
